# Generated by Django 3.1.4 on 2021-07-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210711_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mirror',
        ),
    ]
