# Generated by Django 3.1.4 on 2021-07-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
