# Generated by Django 3.2.5 on 2021-07-30 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_mirror_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirror',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
